#SYSTEM
config:
updater:
history:
sun:
map:
http: !include cfg/http.yaml
homeassistant:
  name: Casa Aloni
  unit_system: metric
  time_zone: Europe/Rome
  elevation: 240
  customize: !include cfg/customize.yaml
frontend:
  javascript_version: latest
  themes: !include_dir_merge_named cfg/themes
recorder:
  purge_interval: 2
  purge_keep_days: 5
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - script
      - sensor.netdata
    entities:
      - sun.sun
      - camera.domodossola
      - sensor.disk_use_root
      - sensor.disk_use_mntusb_1
      - sensor.last_boot
      - sensor.since_last_boot
#DISPOSITIVI E NOTIFICHE
notify:
  - platform: pushbullet
    api_key: !secret pbul
    name: homeassistant
  - platform: zanzito
    device-name: lenovop2
mqtt:
  broker: !secret mqttsrv
  port: 10972
  username: !secret mqttusr
  password: !secret mqttpwd
cloud:
  google_actions:
    filter:
      include_domains:
        - switch
        - light
        - script
        - scene
        - device_tracker
#GATEWAY
hue: !include cfg/gateway/hue.yaml
xiaomi_aqara: !include cfg/gateway/xiaomi.yaml
#DNS 
duckdns: !include cfg/dns/duckdns.yaml
namecheapdns: !include cfg/dns/namecheap.yaml
#INCLUDES
automation: !include cfg/automations.yaml
camera: !include cfg/camera.yaml
device_tracker: !include cfg/device_tracker.yaml
group: !include cfg/groups.yaml
input_number: !include cfg/input_number.yaml
input_select: !include cfg/input_select.yaml
light: !include cfg/light.yaml
logger: !include cfg/logger.yaml
media_player: !include_dir_merge_list cfg/media_players
panel_iframe: !include cfg/iframe.yaml
script: !include cfg/scripts.yaml
sensor: !include_dir_merge_list cfg/sensors
shell_command: !include cfg/shell_command.yaml
switch: !include cfg/switch.yaml
tts: !include cfg/tts.yaml
weblink: !include cfg/weblink.yaml
zone: !include zone.yaml


#DISABLED
#netatmo:
#  api_key: !secret netatmoapi
# secret_key: !secret netatmosecd
#  username: !secret netatmoma
#  password: !secret netatmopwd
#scene: !include_dir_merge_list scene
#input_boolean: !include_dir_merge_named input_boolean
#google_assistant: !include cfg/assistant.yaml
#discovery:
#logbook:

